# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPoll', '0002_votecounter_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='facultyName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='half',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('groupName', 'year', 'faculty')]),
        ),
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together=set([('group', 'subject', 'semester')]),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set([('lName', 'fName', 'mName')]),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('faculty', 'startYear', 'endYear', 'half')]),
        ),
        migrations.AlterUniqueTogether(
            name='votecounter',
            unique_together=set([('vote', 'group', 'course')]),
        ),
    ]
